version: '3.9'

services:
  my_sql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: jewelry
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build: 
      dockerfile: Dockerfile
    depends_on:
      - my_sql
    ports:
      - 8080:8080
  react:
    build: 
      dockerfile: /frontend/Dockerfile
    ports:
      - 3000:3000