spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://my_sql:3306/jewelry
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
mail:
  username: sedman144@gmail.com
  password: xtrv wdcj rgvy dcbf
